"""Build a local x86_64 EFI iPXE and install it as the served ipxe.efi."""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import threading
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from sqlmodel import Session

from .db import session_scope
from .inventory.service import record_activity
from .models import IpxeBuild, IpxeBuildStatus, utcnow
from .settings import get_settings
from .tftp_store import tftp_root

LOGGER = logging.getLogger("home_lab_pxe")

# Keep this SHA in sync with the Dockerfile clone.
IPXE_COMMIT = "7cd92e01d6514b2c8091999f9bce8aef22a1d586"
IPXE_BUILD_ID = 1
IMAGE_SOURCE = Path("/usr/share/home-lab-pxe/ipxe")
WORK_TREE = Path("/tmp/home-lab-pxe-ipxe")
_SECRET_ENV = frozenset({"SECRET_KEY", "ENCRYPTION_KEY", "ADMIN_PASSWORD", "PXE_SMB_PASSWORD"})
NATIVE_NAME = "ipxe-native.efi"
CUSTOM_NAME = "ipxe-custom.efi"
SERVED_NAME = "ipxe.efi"
NOTE_NAME = "ipxe-custom.txt"
_MAKE_TIMEOUT_SECONDS = 900
_ERROR_LIMIT = 500

_guard = threading.Lock()
_thread: threading.Thread | None = None
_pending = False


class IpxeBuildError(ValueError):
    pass


@dataclass(frozen=True)
class UsbBuildOptions:
    usb_keyboard: bool = False
    usb_block: bool = True
    hcd_ehci: bool = True
    hcd_uhci: bool = True
    hcd_xhci: bool = True
    hcd_usbio: bool = False

    def symbols(self) -> tuple[tuple[str, bool], ...]:
        return (
            ("USB_HCD_EHCI", self.hcd_ehci),
            ("USB_HCD_UHCI", self.hcd_uhci),
            ("USB_HCD_XHCI", self.hcd_xhci),
            ("USB_HCD_USBIO", self.hcd_usbio),
            ("USB_BLOCK", self.usb_block),
            ("USB_KEYBOARD", self.usb_keyboard),
        )

    @classmethod
    def from_row(cls, row: IpxeBuild) -> UsbBuildOptions:
        return cls(
            usb_keyboard=bool(row.usb_keyboard),
            usb_block=bool(row.usb_block),
            hcd_ehci=bool(row.hcd_ehci),
            hcd_uhci=bool(row.hcd_uhci),
            hcd_xhci=bool(row.hcd_xhci),
            hcd_usbio=bool(row.hcd_usbio),
        )


def render_usb_local_header(options: UsbBuildOptions) -> str:
    """Local usb.h included after iPXE's EFI defaults, so #define USB_KEYBOARD wins."""
    lines = ["/* Generated by home-lab-pxe. Included after the EFI USB defaults. */"]
    for name, enabled in options.symbols():
        lines.append(f"#define {name}" if enabled else f"#undef {name}")
    lines.append("")
    return "\n".join(lines)


def get_or_create_ipxe_build(db: Session) -> IpxeBuild:
    row = db.get(IpxeBuild, IPXE_BUILD_ID)
    if row is not None:
        return row
    row = IpxeBuild(id=IPXE_BUILD_ID)
    db.add(row)
    db.flush()
    return row


def seed_ipxe_build() -> None:
    from .db import SessionLocal, get_engine

    get_engine()
    assert SessionLocal is not None
    with SessionLocal() as db:
        get_or_create_ipxe_build(db)
        db.commit()


def rebuild_in_progress() -> bool:
    with _guard:
        return _pending or (_thread is not None and _thread.is_alive())


def stock_backup_available() -> bool:
    path = tftp_root() / NATIVE_NAME
    return path.is_file() and path.stat().st_size > 0


def apply_options(row: IpxeBuild, options: UsbBuildOptions) -> None:
    row.usb_keyboard = options.usb_keyboard
    row.usb_block = options.usb_block
    row.hcd_ehci = options.hcd_ehci
    row.hcd_uhci = options.hcd_uhci
    row.hcd_xhci = options.hcd_xhci
    row.hcd_usbio = options.hcd_usbio


def begin_rebuild(db: Session, options: UsbBuildOptions, *, actor: str) -> IpxeBuild:
    global _pending
    with _guard:
        if _pending or (_thread is not None and _thread.is_alive()):
            raise IpxeBuildError("A rebuild is already running")
        row = get_or_create_ipxe_build(db)
        apply_options(row, options)
        row.status = IpxeBuildStatus.building.value
        row.error = ""
        db.add(row)
        record_activity(db, actor=actor, action="boot-menu.ipxe-build", detail="started")
        _pending = True
        return row


def cancel_rebuild_pending() -> None:
    global _pending
    with _guard:
        _pending = False


def launch_rebuild() -> None:
    global _pending, _thread
    with _guard:
        _pending = False
        if _thread is not None and _thread.is_alive():
            return
        _thread = threading.Thread(target=_rebuild_job, name="ipxe-build", daemon=True)
        _thread.start()


def restore_stock(db: Session, *, actor: str) -> None:
    if rebuild_in_progress():
        raise IpxeBuildError("A rebuild is already running")
    restore_stock_efi(tftp_root())
    row = get_or_create_ipxe_build(db)
    row.served = "stock"
    db.add(row)
    record_activity(db, actor=actor, action="boot-menu.ipxe-stock", detail=NATIVE_NAME)


def install_built_efi(
    tftp: Path,
    efi: bytes,
    *,
    header: str,
    commit: str,
    built_at: datetime,
    map_text: str,
    require_usbkbd: bool,
) -> None:
    if not efi.startswith(b"MZ") or len(efi) < 64:
        raise IpxeBuildError("Build did not produce an EFI image")
    if require_usbkbd and "usbkbd_driver" not in map_text:
        raise IpxeBuildError("USB keyboard driver was not linked")
    tftp.mkdir(parents=True, exist_ok=True)
    native = tftp / NATIVE_NAME
    current = tftp / SERVED_NAME
    if not native.is_file() and current.is_file() and current.stat().st_size > 0:
        _atomic_write(native, current.read_bytes())
    _atomic_write(tftp / CUSTOM_NAME, efi)
    _atomic_write(current, efi)
    note = (
        f"iPXE {commit}\n"
        f"built_at: {built_at.isoformat()}\n"
        "licence: GPL-2.0-only (iPXE). Not covered by the MIT licence of home-lab-pxe.\n"
        "local config src/config/local/usb.h:\n"
        f"{header}"
    )
    _atomic_write_text(tftp / NOTE_NAME, note)


def restore_stock_efi(tftp: Path) -> None:
    native = tftp / NATIVE_NAME
    if not native.is_file() or native.stat().st_size == 0:
        raise IpxeBuildError("No stock ipxe.efi backup yet")
    _atomic_write(tftp / SERVED_NAME, native.read_bytes())


def _atomic_write(path: Path, data: bytes) -> None:
    tmp = path.parent / f".{path.name}.partial"
    tmp.write_bytes(data)
    tmp.replace(path)


def _atomic_write_text(path: Path, text: str) -> None:
    _atomic_write(path, text.encode("utf-8"))


def _source_tree() -> Path:
    override = (os.getenv("PXE_IPXE_SOURCE") or "").strip()
    return Path(override) if override else IMAGE_SOURCE


def _work_tree_dir() -> Path:
    override = (os.getenv("PXE_IPXE_WORK") or "").strip()
    return Path(override) if override else WORK_TREE


def _browser_roots() -> tuple[Path, ...]:
    settings = get_settings()
    roots: list[Path] = []
    for path in (settings.data_dir, settings.image_root, settings.tftp_root):
        try:
            roots.append(path.resolve())
        except OSError:
            continue
    return tuple(roots)


def path_is_under(path: Path, roots: tuple[Path, ...]) -> bool:
    try:
        resolved = path.resolve()
    except OSError:
        return True
    for root in roots:
        if resolved == root or root in resolved.parents:
            return True
    return False


def _is_under_browser(path: Path) -> bool:
    return path_is_under(path, _browser_roots())


def ensure_work_tree() -> Path:
    """Copy the pinned image source to a directory the Files browser cannot write."""
    source = _source_tree()
    dest = _work_tree_dir()
    if _is_under_browser(source) or _is_under_browser(dest):
        raise IpxeBuildError("iPXE build must use the image source, outside the Files volumes")
    if not (source / "src" / "Makefile").is_file():
        raise IpxeBuildError("iPXE source is not in this image")
    leftover = get_settings().data_dir / "ipxe-src"
    if leftover.exists():
        shutil.rmtree(leftover, ignore_errors=True)
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(source, dest, symlinks=True)
    return dest


def _make_env() -> dict[str, str]:
    return {key: value for key, value in os.environ.items() if key not in _SECRET_ENV}


def read_link_map(bin_dir: Path) -> str:
    preferred = bin_dir / "ipxe.efi.tmp.map"
    if preferred.is_file():
        return preferred.read_text(encoding="utf-8", errors="replace")
    maps = sorted(bin_dir.glob("ipxe*.map"))
    if not maps:
        return ""
    return maps[-1].read_text(encoding="utf-8", errors="replace")


def compile_ipxe(header: str) -> tuple[bytes, str]:
    work = ensure_work_tree()
    local = work / "src" / "config" / "local"
    local.mkdir(parents=True, exist_ok=True)
    (local / "usb.h").write_text(header, encoding="utf-8")
    jobs = str(max(1, os.cpu_count() or 1))
    _run_make(work, ["make", "-C", "src", "clean"])
    _run_make(work, ["make", "-C", "src", "-j", jobs, "bin-x86_64-efi/ipxe.efi"])
    bin_dir = work / "src" / "bin-x86_64-efi"
    efi_path = bin_dir / "ipxe.efi"
    if not efi_path.is_file():
        raise IpxeBuildError("Build did not produce an EFI image")
    return efi_path.read_bytes(), read_link_map(bin_dir)


def _run_make(work: Path, cmd: list[str]) -> None:
    try:
        proc = subprocess.run(
            cmd,
            cwd=work,
            capture_output=True,
            text=True,
            timeout=_MAKE_TIMEOUT_SECONDS,
            check=False,
            env=_make_env(),
        )
    except FileNotFoundError as exc:
        raise IpxeBuildError("The iPXE compiler tools are not installed in this image") from exc
    except subprocess.TimeoutExpired as exc:
        raise IpxeBuildError("iPXE build timed out") from exc
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout or "").strip()
        detail = tail[-_ERROR_LIMIT:] if tail else f"make exited {proc.returncode}"
        raise IpxeBuildError(detail)


def _rebuild_job() -> None:
    try:
        with session_scope() as db:
            options = UsbBuildOptions.from_row(get_or_create_ipxe_build(db))
        header = render_usb_local_header(options)
        efi, map_text = compile_ipxe(header)
        built_at = utcnow()
        install_built_efi(
            tftp_root(),
            efi,
            header=header,
            commit=IPXE_COMMIT,
            built_at=built_at,
            map_text=map_text,
            require_usbkbd=options.usb_keyboard,
        )
    except Exception as exc:
        LOGGER.warning("ipxe build failed: %s", exc)
        message = str(exc).strip() or "Rebuild failed"
        with session_scope() as db:
            row = get_or_create_ipxe_build(db)
            row.status = IpxeBuildStatus.failed.value
            row.error = message[:_ERROR_LIMIT]
            record_activity(db, actor="ipxe-build", action="boot-menu.ipxe-build", detail=row.error)
            db.commit()
        return
    with session_scope() as db:
        row = get_or_create_ipxe_build(db)
        row.status = IpxeBuildStatus.ready.value
        row.error = ""
        row.served = "custom"
        row.source_commit = IPXE_COMMIT
        row.built_at = built_at
        record_activity(db, actor="ipxe-build", action="boot-menu.ipxe-build", detail=CUSTOM_NAME)
        db.commit()


def display_state(row: IpxeBuild) -> tuple[str, str, bool]:
    """Status, error text, and whether a build thread is still running."""
    running = rebuild_in_progress()
    if row.status == IpxeBuildStatus.building.value and not running:
        return IpxeBuildStatus.failed.value, row.error or "Rebuild stopped before it finished", False
    return row.status, row.error, running
